---
- hosts: develop
  become: yes
  user: vagrant
  tasks:
    - name: Install nginx repository
      yum:
        name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
        state: present
    - name: Install nginx
      yum:
        name: nginx
        state: present
    - name: Starting nginx
      service:
        name: nginx
        state: started
    - name: yum install with_items
      yum:
        name: '{{ item.name }}'
        state: present
      register: RESULT
      with_items:
        - name: git
        - name: gcc
        - name: gcc-c++
        - name: make
        - name: openssl-devel
        - name: bzip2-devel
        - name: zlib-devel
        - name: readline-devel
        - name: sqlite-devel
        - name: bzip2
        - name: sqlite
        - name: patch
        - name: python-psycopg2
    - name: results
      debug: var=RESULT.results
    - name: Install anyenv
      git:
        repo: https://github.com/riywo/anyenv
        dest: /home/vagrant/.anyenv
    - name: change ~/.anyenv owner to vagrant
      file:
        path: /home/vagrant/.anyenv
        state: directory
        owner: vagrant
        group: vagrant
        recurse: yes
    - name: Add ~/.anyenv/bin to PATH
      lineinfile:
        dest="/home/vagrant/.bashrc"
        line="export PATH=$HOME/.anyenv/bin:$PATH"
    - name: Eval anyenv init in ~/.bash_profile
      lineinfile:
        dest="/home/vagrant/.bashrc"
        line='eval "$(anyenv init -)"'
    - name: Reload ~/.bash_profile
      become_user: vagrant
      shell: "exec $SHELL -l"
    - name: Install pyenv
      become_user: vagrant
      shell: "anyenv install pyenv"
      ignore_errors: yes
    - name: Install Python 3.6.5
      become_user: vagrant
      shell: "pyenv install 3.6.5"
      ignore_errors: yes
    - name: Specify vagrant user Global Python version
      become_user: vagrant
      shell: "pyenv global 3.6.5"
    - name: Install Python packages
      become_user: vagrant
      shell: "pip install psycopg2"
      ignore_errors: yes
    - name: Install Postgresql official yum repository
      yum:
        name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
        state: present
    - name: Install Postgresql
      yum:
        name: '{{ item.name }}'
        state: present
      with_items:
        - name: postgresql10
        - name: postgresql10-server
    - stat: path=/var/lib/pgsql/10/data/PG_VERSION
      register: dbcluster
    - name: initdb
      shell: /usr/pgsql-10/bin/postgresql-10-setup initdb
      when: not dbcluster.stat.exists
    - name: start postgresql server
      service:
        name: postgresql-10
        state: started
    - name: Create django User
      become: true
      become_user: postgres
      postgresql_user:
        name: django
        password: password
        encrypted: yes
        role_attr_flags: CREATEDB,NOSUPERUSER
