---
- name: Install Postgresql official yum repository
  become: true
  yum:
    name: "{{ postgresql_repo }}"
    state: present

- name: Install Postgresql
  become: true
  yum:
    name: '{{ item.name }}'
    state: present
  with_items:
    - name: postgresql10
    - name: postgresql10-server

- stat: path=/var/lib/pgsql/10/data/PG_VERSION
  become: true
  register: dbcluster
- name: initdb
  become: true
  shell: /usr/pgsql-10/bin/postgresql-10-setup initdb
  when: not dbcluster.stat.exists

- name: Copy pg_hba.conf
  become: true
  copy:
    src: files/pg_hba.conf
    dest: /var/lib/pgsql/10/data

- name: start postgresql server
  become: true
  service:
    name: postgresql-10
    state: started
    enabled: yes
